DYNDNS_UPDATER_VERSION = none
DYNDNS_UPDATER_SITE = $(WORKSPACE_TOPLEVEL)/package/dyndns-updater
DYNDNS_UPDATER_SITE_METHOD = local
DYNDNS_UPDATER_DEPENDENCIES = bind libcurl

define DYNDNS_UPDATER_INSTALL_TARGET_CMDS
	$(MAKE) -C $(@D) DESTDIR=$(TARGET_DIR) PREFIX=/usr install
endef

$(eval $(generic-package))
